library(monocle)
library(Matrix)
library(ggplot2)

setwd('/data/atimms/cherry_single_cell_0717/seurat_de_1217')


##all samples and data --- add new data
HSMM_expr_matrix <- read.table("retina_seurat_0817.raw_martix.txt",header=T,row.names = 1)
HSMM_sample_sheet <- read.table("retina_seurat_1217.sample_sheet.txt",header=T,row.names = 1)
HSMM_gene_annotation <- read.table("retina_seurat_0817.gene_ann.txt",header=T,row.names = 1)
pd <- new("AnnotatedDataFrame", data = HSMM_sample_sheet)
fd <- new("AnnotatedDataFrame", data = HSMM_gene_annotation)
HSMM <- newCellDataSet(as.matrix(HSMM_expr_matrix), phenoData = pd, featureData = fd,
                       expressionFamily=negbinomial.size())
HSMM = estimateSizeFactors(HSMM)
HSMM = estimateDispersions(HSMM)

##do all the tests
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc034","sc1")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc034_sc1.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc034","sc10")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc034_sc10.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc034","sc12")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc034_sc12.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc034","sc13")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc034_sc13.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc034","sc2911")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc034_sc2911.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc034","sc5")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc034_sc5.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc034","sc6")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc034_sc6.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc034","sc7")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc034_sc7.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc034","sc8")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc034_sc8.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc1","sc034")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc1_sc034.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc1","sc10")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc1_sc10.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc1","sc12")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc1_sc12.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc1","sc13")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc1_sc13.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc1","sc2911")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc1_sc2911.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc1","sc5")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc1_sc5.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc1","sc6")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc1_sc6.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc1","sc7")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc1_sc7.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc1","sc8")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc1_sc8.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc10","sc034")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc10_sc034.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc10","sc1")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc10_sc1.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc10","sc12")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc10_sc12.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc10","sc13")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc10_sc13.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc10","sc2911")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc10_sc2911.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc10","sc5")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc10_sc5.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc10","sc6")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc10_sc6.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc10","sc7")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc10_sc7.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc10","sc8")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc10_sc8.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc12","sc034")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc12_sc034.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc12","sc1")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc12_sc1.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc12","sc10")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc12_sc10.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc12","sc13")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc12_sc13.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc12","sc2911")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc12_sc2911.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc12","sc5")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc12_sc5.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc12","sc6")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc12_sc6.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc12","sc7")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc12_sc7.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc12","sc8")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc12_sc8.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc13","sc034")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc13_sc034.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc13","sc1")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc13_sc1.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc13","sc10")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc13_sc10.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc13","sc12")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc13_sc12.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc13","sc2911")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc13_sc2911.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc13","sc5")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc13_sc5.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc13","sc6")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc13_sc6.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc13","sc7")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc13_sc7.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc13","sc8")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc13_sc8.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc2911","sc034")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc2911_sc034.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc2911","sc1")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc2911_sc1.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc2911","sc10")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc2911_sc10.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc2911","sc12")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc2911_sc12.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc2911","sc13")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc2911_sc13.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc2911","sc5")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc2911_sc5.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc2911","sc6")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc2911_sc6.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc2911","sc7")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc2911_sc7.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc2911","sc8")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc2911_sc8.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc5","sc034")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc5_sc034.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc5","sc1")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc5_sc1.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc5","sc10")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc5_sc10.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc5","sc12")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc5_sc12.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc5","sc13")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc5_sc13.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc5","sc2911")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc5_sc2911.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc5","sc6")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc5_sc6.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc5","sc7")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc5_sc7.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc5","sc8")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc5_sc8.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc6","sc034")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc6_sc034.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc6","sc1")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc6_sc1.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc6","sc10")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc6_sc10.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc6","sc12")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc6_sc12.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc6","sc13")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc6_sc13.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc6","sc2911")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc6_sc2911.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc6","sc5")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc6_sc5.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc6","sc7")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc6_sc7.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc6","sc8")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc6_sc8.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc7","sc034")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc7_sc034.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc7","sc1")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc7_sc1.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc7","sc10")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc7_sc10.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc7","sc12")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc7_sc12.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc7","sc13")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc7_sc13.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc7","sc2911")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc7_sc2911.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc7","sc5")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc7_sc5.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc7","sc6")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc7_sc6.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc7","sc8")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc7_sc8.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc8","sc034")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc8_sc034.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc8","sc1")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc8_sc1.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc8","sc10")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc8_sc10.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc8","sc12")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc8_sc12.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc8","sc13")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc8_sc13.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc8","sc2911")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc8_sc2911.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc8","sc5")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc8_sc5.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc8","sc6")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc8_sc6.de.csv")
sample_subset <- row.names(subset(pData(HSMM), s_cluster %in% c("sc8","sc7")))
diff_test_res <- differentialGeneTest(HSMM[, sample_subset], fullModelFormulaStr="~s_cluster + donor", reducedModelFormulaStr ='~donor')
write.csv(diff_test_res, file = "retina_seurat_1217.sc8_sc7.de.csv")


##get average expression value
## extract expression values
cds_exprs <- exprs(HSMM)
## transpose
cds_exprs <- Matrix::t(cds_exprs)
## compute relative expression?
##cds_exprs <- Matrix::t(cds_exprs)/sizeFactors(HSMM)
## sample info
cds_pData <- pData(HSMM)
## gene names
cds_fData <- fData(HSMM)
## add sample info to expression matrix
cds_exprs = merge(cds_exprs, cds_pData, by="row.names")
## compute mean expression for each gene, grouped by cluster
cds_exprs_mean = aggregate(cds_exprs[, row.names(cds_fData)],
                           list(cds_exprs$s_cluster), mean)
## transpose and then write out file
cds_exprs_mean <- Matrix::t(cds_exprs_mean)
dimnames(cds_exprs_mean)[[2]] = cds_exprs_mean[1,]

cds_exprs_mean = cds_exprs_mean[2:nrow(cds_exprs_mean),]
cds_exprs_mean_char = cds_exprs_mean
cds_exprs_mean = as.numeric(cds_exprs_mean)
attributes(cds_exprs_mean) = attributes(cds_exprs_mean_char)
write.csv(cds_exprs_mean, file = "retina_seurat_1217.mean_expression_per_cluster.csv")


